version: '3.4'
services:
  todo-app:
    container_name: my-todo-app
    build: .
    ports:
      - 3000:3000
  mongodb:
    volumes:
      - todo-app-data:/data/db
    image: mongo
    ports:
      - 27017:27017
volumes:
  todo-app-data:
