version: '3.4'
services:
  uploader-app:
    container_name: my-file-uploader
    build: .
    ports:
      - 3000:3000
    volumes:
      - uploader-app-uploads:/uploads
volumes:
  uploader-app-uploads: